test = input("Professor: Welcome to the world of Pokemon")
print(" ")
test = input("Professor: Paul will show you around")
print(" ")
test = input("Paul: Nice to meet you, my name is Paul")
print(" ")
test = input("Paul: Let's go find some Pokemon")
print(" ")
test = input("Go to the grass and soon enough you will find a Pokemon")